# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b80a37d4b5448776d4ef1faff82a99dbb502eb8a34c9a664d0fecbe48acd18ecdf64b1b09fc43186050f60d6da55e39ec3256b6208797b637dc1b702e15d8f5e

test:
  secret_key_base: 1fc6b7e3608b125fa85b309269c37ccc5ebcb477d9823cffc4eebd7d3b1075ad12a044bf7cddd00c52785fc3f62862f92beafe5049c7ee0cac735c864ec39a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
